image: $DOCKER_TAG

process:
  script:
    - git submodule add https://github.com/200ok-ch/okdoc.git
    - ln -s okdoc/Makefile Makefile
    - make ci push
  except:
    variables:
      - $GITLAB_USER_LOGIN =~ /200ok-bot/
