image: $DOCKER_TAG

process:
  script:
    - git submodule init
    - git config submodule.okdoc.url https://github.com/200ok-ch/okdoc.git
    - git submodule update
    - (cd okdoc; bundle install)
    - ln -fs okdoc/Makefile Makefile
    - make ci push
  except:
    variables:
      - $GITLAB_USER_LOGIN =~ /200ok-bot/
